- name: mongodb
  hosts: catalogue
  become: yes
  tasks:

  - name: "disable and enable nodejs"
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: "install nodejs"
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: "create roboshop"
    ansible.bulitin.user:
      name: roboshop

  - name: "create directory"
    ansible.builtin.file:
      name: /app
      state: diectory

  - name: "downloading code"
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: "unzip the code file"
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: "install dependencies"
    ansible.builtin.gcommand: npn install
      args:
        chdir: /app

  - name: "copy catalogue.service"
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service 

  - name: "daemon_reloa and start"
    ansible.builtin.systemd_service:
      daemon_reload: true

  # - name: "Setup the MongoDB repo file"
  #   ansible.builtin.copy: 
  #     src: mongo.repo 
  #     dest: /etc/yum.repos.d/mongo.repo

  # - name: "install mangodb cliaent"
  #   ansible.builtin.package: 
  #     name: mongodb-client
  #     state: present
  
  # - name: "get the catelogue count"
  #   ansible.builtin.command: mongo', '--host', '44.200.128.125', '--quiet', '--eval', 'db = db.getSiblingDB(\"catalogue\"); db.products.count()'
  #     register: count

  # - name: "print the product count"
  #   ansible.builtin.debug:
  #     msg: "Product count:{{count}}"  

  # - name: "load the catologue data"
  #   ansible.builtin.command: mongo --host 44.200.128.125 </app/schema/catalogue.js
  #   when: count.stdout == 0
  
  - name: "enabled and started catalogue"
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes
    