 
- name: rabbitmq
  hosts: rabbitmq
  become: yes
  tasks: 

  - name: "configure yum erlong repos"
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

  - name: "configure yum rabbitmq repos"
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

  - name: "install rabbitmq"
    ansible.builtin.package:
      name: rabbitmq-serve
      state: present
 
  - name: "enabled and started rabbitmq-server"
    ansible.builtin.service:
      name: rabbitmq-serve
      state: restarted
      enabled: yes

  - name: "create user"
    ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

  - name: "set permissions"
    ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"


  
